### ISSUE TITLE
Add `[hide-until-ready]` attribute

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kelp#101]
For hiding web components that require JS to be useful.

The `[hide-until-ready]` attribute styles it with `display: none`, and the `[is-ready]` attribute (added by the Kelp web components) displays it.

```css
[hide-until-ready]:not([is-ready]) {
    display: none;
}
```
