### ISSUE TITLE
Use native oklch() function to generate color shades

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kelp#107]
It would make theming a lot simpler.

```css
:root {
    --color-red-base: #e50000;
    --color-red-05: oklch(from var(--color-red-base) 18.5 8 h);
    /* ... */
}
```

- [MDN ref](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch)
- [Browser Support](https://caniuse.com/css-relative-colors)
- [Open Props example](https://argyle.ink/open-props-oklch-palettes-beta)
