### ISSUE TITLE
Add styling for `input[type="search"]`

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kelp#114]
[Though that might actually not be a good idea...](https://adrianroselli.com/2019/07/ignore-typesearch.html)

```css
input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none;
  appearance: none;
  background-image: ''; /* Style the icon here */
  cursor: pointer;
}
```
