### ISSUE TITLE
Using light-dark() function for theme?

### ISSUE THREAD

**Issue by rahatbd** [cferdinandi/kelp#81]
**Is your feature request related to a problem? Please describe.**

Hi Chris, I was reading your blog post about [theme](https://gomakethings.com/how-to-create-light-and-dark-color-modes-with-css/) and I was wondering if you have considered the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) css function?

You can then also use the color-scheme property to force a light or dark theme.

**Describe the solution you'd like**
```css
:where(:root) {
    color-scheme: light dark;
    --color-primary-fill-muted: light-dark(var(--color-blue-95), var(--color-blue-20));
}

.kelp-theme-light {
    color-scheme: light;
}

.kelp-theme-dark {
    color-scheme: dark;
}

```
